### ISSUE TITLE
Worked nearly perfectly

### ISSUE THREAD

**Issue by atbe** [kyle-pena-nlp/distr_mflux#1]
Needed to create the `generated` folder otherwise it would error on saving 

```
Traceback (most recent call last):
  File "/Users/ibrahimahmed/code/kuzco/hiring/kyle-pena/distr_mflux/server/.venv/lib/python3.12/site-packages/nats/aio/subscription.py", line 316, in _wait_for_msgs
    await self._cb(msg)
  File "/Users/ibrahimahmed/code/kuzco/hiring/kyle-pena/distr_mflux/requester/requester.py", line 53, in receive_generated_image
    img.save(img_fpath)
  File "/Users/ibrahimahmed/code/kuzco/hiring/kyle-pena/distr_mflux/server/.venv/lib/python3.12/site-packages/PIL/Image.py", line 2563, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ibrahimahmed/code/kuzco/hiring/kyle-pena/distr_mflux/generated/_INBOX.JcX6HPkqDqbdvYgm6qEe8U.png'
```

Otherwise it worked perfectly.

<img width="2056" alt="image" src="https://github.com/user-attachments/assets/037978c1-a72e-4887-96f0-195a1d3fff70">

**Comment by kyle-pena-nlp** [comment]
Oops!  Thank you Abe.
